#include <stdlib.h>
#include <stdio.h>

// include the header file
#include "myjit/jitlib.h"

// pointer to a function accepting one argument of type long and returning long value
typedef long (* plfl)(long);

int main()
{
	// we create a new instance of a compiler
	struct jit * p = jit_init();

	plfl factorial;

	// the code generated by the compiler will be assigned to the function `foo'
	jit_prolog(p, &factorial);

	// first argument of the function
	jit_declare_arg(p, JIT_SIGNED_NUM, sizeof(long));

	// moves the first argument into the register R(0)
	jit_getarg(p, R(0), 0);

	// register R(1) serves as an accumulator
	jit_movi(p, R(1), 1);

	// here starts the loop
	jit_label * loop = jit_get_label(p);
	
	// if the value of R(0) is lesser or equal than 0, 
	// jump to the line jit_patch(jit, o);
	// an example of the forward declaration
	jit_op * o = jit_blei(p, JIT_FORWARD, R(0), 0);

	// multiplies the value of R(1) by R(0) and stores the result into the register R(1)
	jit_mulr(p, R(1), R(1), R(0));

	// decrements the value of R(0) by one
	jit_subi(p, R(0), R(0), 1);

	// jumps to the beginning of the loop
	jit_jmpi(p, loop);

	jit_patch(p, o);
	
	// returns the factorial
	jit_retr(p, R(1));

	// compiles the above defined code
	jit_generate_code(p);
	jit_dump_ops(p, JIT_DEBUG_CODE);

	// check
	printf("Check #1: 1! = %li\n", factorial(1));
	printf("Check #2: 5! = %li\n", factorial(5));
	printf("Check #3: 6! = %li\n", factorial(6));

	// cleanup
	jit_free(p);
	return 0;
}
