#include <stdlib.h>
#include <stdio.h>

// include the header file
#include "myjit/jitlib.h"

// pointer to a function accepting one argument of type long and returning long value
typedef long (* plfl)(long);

int main()
{
	// we create a new instance of a compiler
	struct jit * p = jit_init();

	plfl foo;

	// the code generated by the compiler will be assigned to the function `foo'
	jit_prolog(p, &foo);

	// the first argument of the function is signed number of size `long'
	jit_declare_arg(p, JIT_SIGNED_NUM, sizeof(long));

	// moves the first argument into the register R(0)
	jit_getarg(p, R(0), 0);

	// takes the value in R(0), increments it by one, and stores the result into the
	// register R(1)
	jit_addi(p, R(1), R(0), 1);

	// returns from the function and returns the value in register R(1)
	jit_retr(p, R(1));

	// compiles the above defined code
	jit_generate_code(p);

	// if you are interested, you can dump the machine code
	jit_dump_ops(p, JIT_DEBUG_CODE);

	// check
	printf("Check #1: %li\n", foo(1));
	printf("Check #2: %li\n", foo(100));
	printf("Check #3: %li\n", foo(255));

	// cleanup
	jit_free(p);
	return 0;
}
