#include <stdlib.h>
#include <stdio.h>

// include the header file
#include "myjit/jitlib.h"

// pointer to a function accepting one argument of type long and returning long value
typedef long (* plfl)(long);

int main()
{
	// we create a new instance of a compiler
	// the first indicates number of used registers (4)
	struct jit * p = jit_init(4);

	plfl foo;

	// the code generated by the compiler will be assigned to the function `foo'
	jit_prolog(p, &foo);

	// the first argument of the function
	int ar1 = jit_arg(p);

	// moves the first argument into the register R(0)
	jit_getarg(p, R(0), ar1, sizeof(long));

	// takes the value in R(0), increments it by one, and stores the result into the
	// register R(1)
	jit_movi(p, R(2), 20000000);
	jit_label * loop = jit_get_label(p);
	jit_addi(p, R(1), R(0), 1);

	jit_muli(p, R(1), R(1), -15);
	jit_subi(p, R(2), R(2), 1);
	jit_bgti(p, loop, R(2), 0);

	// returns from the function and returns the value in register R(1)
	jit_retr(p, R(1));

	// compiles the above defined code
	jit_generate_code(p);

	// if you are interested, you can dump the machine code
	// this functionality is provided through the `gcc' and `objdump'
	jit_dump(p);

	// check
	printf("Check #1: %li\n", foo(1));
	printf("Check #2: %li\n", foo(100));
	printf("Check #3: %li\n", foo(255));

	// cleanup
	jit_free(p);
	return 0;
}
